---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 8f68e0670b11883e082d61819042268d6fba737b
    app.quarkus.io/build-timestamp: 2021-06-23 - 08:48:15 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: baaas-master-control-plane
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: baaas-master-control-plane
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 8f68e0670b11883e082d61819042268d6fba737b
    app.quarkus.io/build-timestamp: 2021-06-23 - 08:48:15 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: baaas-master-control-plane
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: baaas-master-control-plane
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: baaas-master-control-plane
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: baaas-master-control-plane-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: baaas-master-control-plane
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 8f68e0670b11883e082d61819042268d6fba737b
    app.quarkus.io/build-timestamp: 2021-06-23 - 08:48:15 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: baaas-master-control-plane
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: baaas-master-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: baaas-master-control-plane
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 8f68e0670b11883e082d61819042268d6fba737b
        app.quarkus.io/build-timestamp: 2021-06-23 - 08:48:15 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: baaas-master-control-plane
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jrota/baaas-master-control-plane:1.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: baaas-master-control-plane
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccount: baaas-master-control-plane
